#!/usr/bin/env sh

# get the mongodb process id
pid=`lunchy status mongodb | awk '{print $1}'`

# stop the mongod process
if [ ! -z $pid ] && [ "$pid" != "-" ]; then
  kill -2 $pid > /dev/null
fi

# remove lock file if present
if [ -f /data/db/current/default/mongod.lock ]; then
  find /data/db -type f -name '*.lock' -ls -delete > /dev/null
fi

# remove symlink if it already exists
if [ -d /data/db/current ]; then
  rm /data/db/current
fi
