#!/usr/bin/env sh

# get current mongodb version
version=`mongod --version | egrep -o 'v[0-9]+\.[0-9]+\.[0-9]+([-_\.][a-zA-Z0-9]+)?'`
version=${version:1}

# create current symlink
if [ ! -z "$version" ]; then
  mkdir -p /data/db/$version/default
  ln -Fs /data/db/$version /data/db/current
fi

# start mongodb
lunchy restart mongodb
